ContradoApp/Models/EnumAndConstant.cs
namespace ContradoApp.Models
{
    public class EnumAndConstant
    {
        
    }

    public enum MessageType
    {
        ErrorMessage,
        SuccessMessage
    }
}

ContradoApp/Models/ErrorViewModel.cs
using System;

namespace ContradoApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ContradoApp/Controllers/HomeController.cs
using ContradoApp.Models;
using ContradoApp.Service.Interface;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Diagnostics;
using System.Threading.Tasks;

namespace ContradoApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IProductCategoryService _productCategoryService;

        public HomeController(ILogger<HomeController> logger, IProductCategoryService productCategoryService)
        {
            _logger = logger;
            _productCategoryService = productCategoryService;
        }

        public async Task<IActionResult> Index()
        {
            var newId = await _productCategoryService.Get(5);
            var newId1 = await _productCategoryService.GetWithDetails(5);
            await _productCategoryService.GetAll();
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ContradoApp/Controllers/ProductController.cs
using ContradoApp.Models;
using ContradoApp.Service.Interface;
using ContradoApp.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace ContradoApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly IProductCategoryService _productCategoryService;

        public ProductController(IProductService productService, IProductCategoryService productCategoryService)
        {
            _productService = productService;
            _productCategoryService = productCategoryService;
        }

        public async Task<IActionResult> Index()
        {
            var prodList = await _productService.GetAll();
            return View(prodList);
        }

        public async Task<IActionResult> CategorySelection()
        {
            var prodCategoryList = await _productCategoryService.GetAll();
            var categorySelection = new CategorySelectionViewModel()
            {
                CategoryData = prodCategoryList.ToList()
            };
            return View(categorySelection);
        }

        [HttpPost]
        public async Task<IActionResult> CategorySelection(int SelectedCategory)
        {
            if (SelectedCategory > 0)
            {
                var categoryData = await _productCategoryService.Get(SelectedCategory);
                if (categoryData != null)
                {
                    return RedirectToAction("CreateOrUpdate", new { categoryId = SelectedCategory });
                }
            }
            return RedirectToAction("CategorySelection");
        }

        public async Task<IActionResult> CreateOrUpdate(int categoryId = 0, int productId = 0)
        {
            var productViewModel = new ProductViewModel();
            if (productId > 0)
            {
                // Edit Product
                productViewModel = await _productService.Get(productId);
                if (productViewModel == null)
                {
                    return RedirectToAction("Index");
                }
            }
            else if (categoryId > 0)
            {
                // Add Product
                var categoryDetails = await _productCategoryService.Get(categoryId);
                if (categoryDetails != null)
                {
                    productViewModel.ProdCatId = categoryId;
                    productViewModel.ProdCatName = categoryDetails.CategoryName;
                }
            }

            if (productViewModel.ProdCatId > 0)
            {
                productViewModel.AttributeAsPerCategory = (await _productService.GetAttributeByCategoryId(productViewModel.ProdCatId))?.ToList();
                return View(productViewModel);
            }

            return RedirectToAction("CategorySelection");
        }

        [HttpPost]
        public async Task<IActionResult> CreateOrUpdate(ProductViewModel productViewModel)
        {
            if (ModelState.IsValid)
            {
                await _productService.Save(productViewModel);
                return RedirectToAction("Index");
            }
            else
            {
                TempData[MessageType.ErrorMessage.ToString()] = string.Join(" | ", ModelState.Values
                    .SelectMany(v => v.Errors)
                    .Select(e => e.ErrorMessage));
                productViewModel.AttributeAsPerCategory = (await _productService.GetAttributeByCategoryId(productViewModel.ProdCatId))?.ToList();
            }
            return View(productViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> AddAttributeSelection(int categoryId, int index = 0)
        {
            if (categoryId > 0)
            {
                var productAttribute = new ProductAttributeViewModel()
                {
                    Index = index
                };
                productAttribute.AttributeSelectionOption = (await _productService.GetAttributeByCategoryId(categoryId))?.ToList();
                return PartialView("_ProductMappedAttribute", productAttribute);
            }
            return Ok();
        }

        [HttpPost]
        public async Task<IActionResult> DeleteAttribute(long productAttributeId)
        {
            if (productAttributeId > 0)
            {
                await _productService.DeleteProductAttribute(productAttributeId);
            }
            return Ok();
        }
    }
}

ContradoApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ContradoApp/Views/Product/CategorySelection.cshtml
@model CategorySelectionViewModel

@{
    ViewData["Title"] = "Product Create - Step 1 - Select Category";
}

<h1> Category Selection</h1>

<h4>Product Create : Step 1</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CategorySelection" method="post">
            
            <div class="form-group">
                @Html.DropDownList("SelectedCategory", new SelectList(
                                        Model.CategoryData.Select(x => new { Value = x.ProdCatId, Text = x.CategoryName }).OrderBy(o => o.Value),
                                        "Value",
                                        "Text",
                                        Model.SelectedCategory),
                                        "Select Category", new { @class = "form-control" })
                <span asp-validation-for="SelectedCategory" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Go To Step 2" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ContradoApp/Views/Product/CreateOrUpdate.cshtml
@model ProductViewModel

@{
    ViewData["Title"] = "Save Product Data";
    int indexCount = 0;
}

<h1> @(Model.ProductId > 0 ? "Edit" : "New") Product</h1>

<h4>Product Details - Step 2 (For Category : @Model.ProdCatName) </h4>
<hr />
<div class="row">
    @await Html.PartialAsync("_RenderErrorMessage")
    <div class="col-md-8">
        <form asp-action="CreateOrUpdate" method="post">
            <input type="hidden" asp-for="ProdCatId" />
            <input type="hidden" asp-for="ProductId" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="ProdName" class="control-label"></label>
                <input asp-for="ProdName" class="form-control" />
                <span asp-validation-for="ProdName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProdDescription" class="control-label"></label>
                <textarea asp-for="ProdDescription" class="form-control"></textarea>
                <span asp-validation-for="ProdDescription" class="text-danger"></span>
            </div>

            <div class="form-group">
                <table id="AttributeList">
                    <thead>
                        <tr>
                            <th>
                                Attribute
                            </th>
                            <th>
                                Value
                            </th>
                            <th>
                                <a href="javascript:;" class="add-row">Add Attribute Row</a>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model.MappedAttribute?.Any() ?? false)
                        {
                            foreach (var eachMappedAttributeDetails in Model.MappedAttribute)
                            {
                                eachMappedAttributeDetails.Index = indexCount;
                                eachMappedAttributeDetails.AttributeSelectionOption = Model.AttributeAsPerCategory;
                                @await Html.PartialAsync("_ProductMappedAttribute", eachMappedAttributeDetails)
                                indexCount++;
                            }
                        }

                    </tbody>
                </table>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

<input type="hidden" value="@Url.Action("AddAttributeSelection")" id="addformurl" />
<input type="hidden" value="@Url.Action("DeleteAttribute")" id="deleteformurl" />

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/CreatePage.js" asp-append-version="true"></script>
}

ContradoApp/Views/Product/Index.cshtml
@model IEnumerable<ProductViewModel>
@{ 
    ViewData["Title"] = "Product List";
}

@section Styles
{
    <link rel="stylesheet" href="//cdn.datatables.net/1.11.0/css/jquery.dataTables.min.css" />
}

<div class="form-group">
    <a class="btn btn-primary" href="@Url.Action("CategorySelection")">Add New Product</a>
</div>
@if (Model?.Any() ?? false)
{
    <table id="ProductTable">
        <thead>
            <tr>
                <th>

                </th>
                <th>
                    Product Name
                </th>
                <th>
                    Category
                </th>
                <th>
                    Product Description
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var eachProduct in Model)
            {
                <tr>
                    <td>
                        <a href="@Url.Action("CreateOrUpdate",new { productId = eachProduct.ProductId })">Edit</a>
                    </td>
                    <td>
                        @eachProduct.ProdName
                    </td>
                    <td>
                        @eachProduct.ProdCatName
                    </td>
                    <td>
                        @eachProduct.ProdDescription
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h1>No Product is added yet, click here to Add new</h1>
}

@section Scripts
{
    <script src="//cdn.datatables.net/1.11.0/js/jquery.dataTables.min.js"></script>
    <script src="~/js/IndexPage.js" asp-append-version="true"></script>
}

ContradoApp/Views/Product/_ProductMappedAttribute.cshtml
@model ProductAttributeViewModel

<tr data-index="@Model.Index">
    <td>
        @Html.DropDownList("MappedAttribute[" + Model.Index + "].AttributeId", new SelectList(
                Model.AttributeSelectionOption.Select(x => new { Value = x.AttributeId, Text = x.AttributeName }),
                "Value",
                "Text",
                Model.AttributeId
    ), "Select Attribute", new { @class = "form-control" })
        <input type="hidden" value="@Model.ProductAttributeId" name="@("MappedAttribute[" + Model.Index + "].ProductAttributeId")" />
        <input type="hidden" value="@Model.ProductId" name="@("MappedAttribute[" + Model.Index + "].ProductId")" />
    </td>
    <td>
        <input type="text" name="@("MappedAttribute[" + Model.Index + "].AttributeValue")" class="form-control" value="@Model.AttributeValue" />
    </td>
    <td>
        <a href="javascript:;" data-deleteId="@Model.ProductAttributeId" class="delete-row">Delete</a>
    </td>
</tr>

ContradoApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ContradoApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ContradoApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ContradoApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ContradoApp/Views/Shared/_RenderErrorMessage.cshtml
@if (TempData != null && TempData.Keys.Any() && TempData.Keys.Contains(MessageType.ErrorMessage.ToString()))
{
    <div class="alert alert-danger alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h4><i class="icon fa fa-ban"></i>Error!</h4>
        @TempData[MessageType.ErrorMessage.ToString()]
    </div>
}